/* gen_asm_data.c - HOST ONLY. Emits the read-only data of the RV32I program
 * from the SAME arrays the C solver uses (c/tables.h), so C and assembly can
 * never disagree about a table.
 *   usage: gen_asm_data [DIR=asm/data] [--word] [--rodata]
 *   writes DIR/tables.inc (QT, PDB_A, PDB_B) and DIR/consts.inc (.equ values)
 *   --word    emit .word (4 bytes per item, little endian) instead of .byte
 *   --rodata  put the tables in `.section .rodata` instead of `.data`
 * Both choices count the same toward the 128 KiB static-data budget. */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "pdb_spec.h"
#include "tables.h"

static unsigned long sum_bytes(const uint8_t *a, size_t n)
{
    unsigned long s = 0;
    for (size_t i = 0; i < n; i++) s += a[i];
    return s;
}

static void emit(FILE *f, const char *label, const uint8_t *a, size_t n, int word)
{
    fprintf(f, "\n# %s: %zu bytes, byte-sum %lu\n.align 2\n%s:\n", label, n, sum_bytes(a, n), label);
    if (word) {
        if (n % 4) { fprintf(stderr, "%s: size not a multiple of 4\n", label); exit(1); }
        for (size_t i = 0; i < n; i += 4) {
            uint32_t v = (uint32_t)a[i] | (uint32_t)a[i + 1] << 8 | (uint32_t)a[i + 2] << 16 | (uint32_t)a[i + 3] << 24;
            fprintf(f, "%s0x%08x", i % 32 ? ", " : (i ? "\n    .word " : "    .word "), v);
        }
        fprintf(f, "\n");
    } else {
        for (size_t i = 0; i < n; i += 16) {
            fprintf(f, "    .byte ");
            for (size_t j = i; j < i + 16 && j < n; j++) fprintf(f, "%s%u", j > i ? ", " : "", a[j]);
            fprintf(f, "\n");
        }
    }
}

int main(int argc, char **argv)
{
    const char *dir = "asm/data";
    int word = 0, rodata = 0;
    char path[512];
    for (int i = 1; i < argc; i++) {
        if (!strcmp(argv[i], "--word")) word = 1;
        else if (!strcmp(argv[i], "--rodata")) rodata = 1;
        else dir = argv[i];
    }
    snprintf(path, sizeof path, "%s/tables.inc", dir);
    FILE *f = fopen(path, "w");
    if (!f) { perror(path); return 1; }
    fprintf(f, "# GENERATED by tools/gen_asm_data.c from c/tables.h - do not edit.\n");
    fprintf(f, "# Labels: QT (96 B), PDB_A, PDB_B (%u B each, nibble packed, even index = low nibble).\n", PDB_BYTES);
    fprintf(f, "# QT[face*32 + x] -> x after one quarter turn, x = position<<2 | twist.\n");
    fprintf(f, "%s\n", rodata ? ".section .rodata" : ".data");
    emit(f, "QT", QT, sizeof QT, word);
    emit(f, "PDB_A", PDB_A_TAB, sizeof PDB_A_TAB, word);
    emit(f, "PDB_B", PDB_B_TAB, sizeof PDB_B_TAB, word);
    fclose(f);

    snprintf(path, sizeof path, "%s/consts.inc", dir);
    f = fopen(path, "w");
    if (!f) { perror(path); return 1; }
    fprintf(f, "# GENERATED by tools/gen_asm_data.c - do not edit.\n");
    fprintf(f, ".equ PDB_ENTRIES, %u\n.equ PDB_BYTES, %u\n", PDB_ENTRIES, PDB_BYTES);
    fprintf(f, "# tracked cubies (internal ids 0..6): set A and set B\n");
    fprintf(f, ".equ A0, %d\n.equ A1, %d\n.equ A2, %d\n.equ A3, %d\n", A0, A1, A2, A3);
    fprintf(f, ".equ B0, %d\n.equ B1, %d\n.equ B2, %d\n.equ B3, %d\n", B0, B1, B2, B3);
    fprintf(f, "# byte sums, for the M1 data-loading milestone\n");
    fprintf(f, ".equ SUM_QT, %lu\n.equ SUM_A, %lu\n.equ SUM_B, %lu\n", sum_bytes(QT, sizeof QT),
            sum_bytes(PDB_A_TAB, sizeof PDB_A_TAB), sum_bytes(PDB_B_TAB, sizeof PDB_B_TAB));
    fclose(f);
    printf("wrote %s/tables.inc (%s%s) and consts.inc: QT %zu B + 2 x %u B = %zu B\n", dir,
           word ? ".word" : ".byte", rodata ? ", .rodata" : ", .data", sizeof QT, PDB_BYTES,
           sizeof QT + 2 * (size_t)PDB_BYTES);
    return 0;
}
