/* gen_tables.c - HOST ONLY. Emits c/tables.h (QT + two nibble-packed PDBs). */
#include <stdio.h>
#include "pdb_build.h"

static void emit(FILE *f, const char *name, const uint8_t *a, size_t n)
{
    fprintf(f, "static const uint8_t %s[%zu] = {", name, n);
    for (size_t i = 0; i < n; i++)
        fprintf(f, "%s%u,", i % 24 ? "" : "\n", a[i]);
    fprintf(f, "\n};\n");
}

int main(int argc, char **argv)
{
    const char *out = argc > 1 ? argv[1] : "c/tables.h";
    static const uint8_t setA[4] = {A0, A1, A2, A3}, setB[4] = {B0, B1, B2, B3};
    uint8_t qt[96];
    static uint8_t dist[2][PDB_ENTRIES], packed[2][PDB_BYTES];
    build_qt(qt);
    for (int t = 0; t < 2; t++) {
        uint32_t n = pdb_bfs(qt, t ? setB : setA, dist[t]);
        uint32_t hist[16] = {0};
        if (n != PDB_ENTRIES) { fprintf(stderr, "table %d: %u/%u reached\n", t, n, PDB_ENTRIES); return 1; }
        memset(packed[t], 0, PDB_BYTES);
        for (uint32_t i = 0; i < PDB_ENTRIES; i++) {
            if (dist[t][i] > 15) { fprintf(stderr, "value > 15\n"); return 1; }
            pdb_set(packed[t], i, dist[t][i]); hist[dist[t][i]]++;
        }
        printf("PDB %c:", 'A' + t);
        for (int d = 0; d < 16; d++) if (hist[d]) printf(" d%d=%u", d, hist[d]);
        printf("\n");
    }
    FILE *f = fopen(out, "w");
    if (!f) { perror(out); return 1; }
    fprintf(f, "/* GENERATED by tools/gen_tables.c - do not edit. */\n");
    fprintf(f, "#ifndef TABLES_H\n#define TABLES_H\n#include <stdint.h>\n");
    fprintf(f, "/* QT[face*32 + x]: x = position<<2 | twist after a quarter turn */\n");
    emit(f, "QT", qt, 96);
    emit(f, "PDB_A_TAB", packed[0], PDB_BYTES);
    emit(f, "PDB_B_TAB", packed[1], PDB_BYTES);
    fprintf(f, "#endif\n");
    fclose(f);
    printf("wrote %s (QT 96 B + 2 x %u B)\n", out, PDB_BYTES);
    return 0;
}
